package softplag;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * 
 * @author Sushant
 */
public  class SoftPlag1 extends javax.swing.JFrame {

    /**
     * Creates new form SoftPlag1
     */
    private String s1;
     private String s2;
    private String  string;
    private static String  str;
    private String  str1;
    private File  f;
    
    private File file1;
    private File file2;
    
    private float finalMValue;
    private float mLayout;
    private float mStructure;
    private float mStyle;
    
    
    public SoftPlag1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.textHighlight);

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Browse");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Check");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 0, 0));
        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("SoftPlag");
        jLabel1.setAutoscrolls(true);
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Plagarism Detecion Tool");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(jTextField2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2))
                .addGap(38, 38, 38)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(262, 262, 262))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        JFileChooser jfc1=new JFileChooser(new File("c:\\"));
        jfc1.setFileFilter(new FileType(".java","Java File"));
        jfc1.showOpenDialog(null);
        file2=jfc1.getSelectedFile();
         
        s2=file2.getName();
        jTextField2.setText(s2);
      /*  String check =   "^[a-zA-Z0-9]{1,50}[.]{1}[java]{1,4}$";
               if (!(Pattern.matches(check,s2 )))
        {            // TODO add your handling code here:
      JOptionPane.showMessageDialog(null,"Error","error", JOptionPane.ERROR_MESSAGE);
            
    }                                        
        else
            {
                 jTextField2.setText(s2);
           
                 
            }*/
        
        
        
        
    }                                        
    
    
    
    private float[] getLayoutValues(File file){
        
        float[] arr = new float[5];
        try {
            
            
            STYCalculator sty = new STYCalculator(file);
            float wmLayout = sty.getWMLayoutValue();
            float wmStyle = sty.getWMStyleValue();
            float wmStructure = sty.getWMStructure();
            
            float weightedMeanSum = sty.getWeightedSumMean();
            float overAllSum = sty.getOverallSum();
            
//            System.out.println(file.getName());
//            System.out.println(wmLayout);
//            System.out.println(wmStyle);
//            System.out.println(wmStructure);
//            System.out.println(overAllSum);
            
            arr[0] = wmLayout;
            arr[1] = wmStyle;
            arr[2] = wmStructure;
            arr[3] = weightedMeanSum;
            arr[4] = overAllSum;
            
            
        } catch (IOException ex) {
            Logger.getLogger(SoftPlag1.class.getName()).log(Level.SEVERE, null, ex);
        }
        return arr;
    }
    
    private String getMetricsInfo(File file){
        String mInfo = "";
        try {
            
            STYCalculator sty = new STYCalculator(file);
            mInfo = sty.getMetricsInfo();
//           System.out.println(file.getAbsolutePath());
//            System.out.println(mInfo);
        
        } catch (IOException ex) {
            System.out.println("fdgh");
            Logger.getLogger(SoftPlag1.class.getName()).log(Level.SEVERE, null, ex);
        }
        return mInfo;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser jfc=new JFileChooser(new File("f:\\"));
        jfc.setFileFilter(new FileType(".java","Java File"));
        jfc.showOpenDialog(null);
        file1=jfc.getSelectedFile();
         str= file1.getAbsolutePath();
 
        s1=file1.getName();
        jTextField1.setText(s1);
      /*  String check =  "^[a-zA-Z0-9]{1,50}[.]{1}[java]{1,4}$";
               if (!(Pattern.matches(check,s1 )))
        {            // TODO add your handling code here:
      JOptionPane.showMessageDialog(null,"Error","error", JOptionPane.ERROR_MESSAGE);
            
    }                                        
        else
            {
                 jTextField1.setText(s1);
           
                 
            }*/
   
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
   
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
     if(!(Pattern.matches("^[a-zA-Z0-9]{1,50}[.]{1}[java]{1,4}$", jTextField1.getText()))){
       JOptionPane.showMessageDialog(null, "Please select java file only","Error",JOptionPane.ERROR_MESSAGE);
        jTextField1.setText(null);
       }
       if(!(Pattern.matches("^[a-zA-Z0-9]{1,50}[.]{1}[java]{1,4}$", jTextField2.getText()))){
       JOptionPane.showMessageDialog(null, "Please select java file only","Error",JOptionPane.ERROR_MESSAGE);
       jTextField2.setText(null);
       }
       
       else{
        dispose();
        
       // System.out.println("Filepath="+str);
      
        
            ResultPage r = new ResultPage();
            float[] layoutValuesFile1 = getLayoutValues(file1);
            float[] layoutValuesFile2 = getLayoutValues(file2);
            
            String metricsInfo1 = getMetricsInfo(file1);
            String metricsInfo2 = getMetricsInfo(file2);
            
//            System.out.println("file 1 " + metricsInfo1);
//            System.out.println("file 2 " + metricsInfo2);
//            
            calculateFinalValue(layoutValuesFile1, layoutValuesFile2);
            r.setmLayout(mLayout);
            r.setmStructure(mStructure);
            r.setmStyle(mStyle);
           // System.out.println("final ");
            //System.out.println("finalmvalue" + finalMValue);
            r.setFinalmValue(finalMValue);
          //  System.out.println(metricsInfo2);
            r.setMetricsInfo(metricsInfo1, metricsInfo2);
            r.displayResult();
            
            
            r.setVisible(true);
       }
            /*        if(jTextField1.equals(null)||jTextField2.equals(null)){
             JOptionPane.showMessageDialog(null,"Please select file");
             
         }  
         else{
             
         }*/
    }//GEN-LAST:event_jButton4ActionPerformed
    private void calculateFinalValue(float[] layoutValuesFile1, float[] layoutValuesFile2){
        float wmLayoutFile1 = layoutValuesFile1[0];
        float wmStyleFile1 = layoutValuesFile1[1];
        float wmStructureFile1 = layoutValuesFile1[2];
        float weightedMeanSum1 = layoutValuesFile1[3];
        float overAllSum1 = layoutValuesFile1[4];
                
        float wmLayoutFile2 = layoutValuesFile2[0];
        float wmStyleFile2 = layoutValuesFile2[1];
        float wmStructureFile2 = layoutValuesFile2[2];
        float weightedMeanSum2 = layoutValuesFile2[3];
        float overAllSum2 = layoutValuesFile2[4];
        
        
        mLayout = (1 - ((Math.abs(wmLayoutFile1 - wmLayoutFile2))/Math.max(wmLayoutFile1, wmLayoutFile2)))* 100;
        mStructure = (1 - ((Math.abs(wmStructureFile1 - wmStructureFile2))/Math.max(wmStructureFile1, wmStructureFile2)))* 100;
        mStyle = (1 - ((Math.abs(wmStyleFile1 - wmStyleFile2))/Math.max(wmStyleFile1, wmStyleFile2)))* 100;
        
        /*System.out.println("mLayout : " + mLayout);
        System.out.println("mstruct : " + mStructure);
        System.out.println("mstyle : " + mStyle);
       
        System.out.println("overAllSum1 : " + overAllSum1);
        System.out.println("overAllSum2 : " + overAllSum2);
        System.out.println("weightedMeanSum1 : + " + weightedMeanSum1);
        System.out.println("weightedMeanSum2 : + " + weightedMeanSum2);*/
        
        float wmValue1 = overAllSum1/weightedMeanSum1;
        float wmValue2 = overAllSum2/weightedMeanSum2;
        
//        System.out.println("wmValue1 " + wmValue1);
//        System.out.println("wmValue2 " + wmValue2);
//        
        finalMValue = (1 - (Math.abs(wmValue1 - wmValue2)/Math.max(wmValue1, wmValue2))) *  100;
//        System.out.println(Math.abs(wmValue1 - wmValue2));
//        System.out.println((Math.abs(wmValue1 - wmValue2)/Math.max(wmValue1, wmValue2)));
//        System.out.println((1 - (Math.abs(wmValue1 - wmValue2)/Math.max(wmValue1, wmValue2))));
//        System.out.println((1 - (Math.abs(wmValue1 - wmValue2)/Math.max(wmValue1, wmValue2))) *  100);
//        
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       
        
        
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SoftPlag1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SoftPlag1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SoftPlag1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SoftPlag1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
         //String string=sp.str;
         //String string1=sp.str1;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SoftPlag1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jButton1
     */
 

    /**
     * @param jButton1 the jButton1 to set
     */
    

    /**
     * @return the jButton3
     */
   
    /**
     * @param jButton3 the jButton3 to set
     */
    
}
